name: Docker Workflow

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t name-app-image .

    - name: Run Docker container
      run: |
        docker run --name name-app-container name-app-image
